# Generated by Django 5.1.6 on 2025-02-10 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProducerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producerName', models.CharField(max_length=100)),
                ('typeOforganization', models.CharField(choices=[('construction', 'Construction and Infrastructure'), ('hospitality', 'Hospitality and Food Services'), ('manufacturing', 'Manufacturing and Production'), ('agriculture', 'Agriculture and Farming'), ('healthcare', 'Healthcare and Medical Services'), ('education', 'Education and Training'), ('retail', 'Retail and Wholesales'), ('transportation', 'Transportation and Automotive'), ('electronics', 'Electronics and Technology'), ('chemical', 'Chemical'), ('pharmaceutical', 'Pharmaceutical')], max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
            ],
        ),
    ]
