# Generated by Django 5.1.6 on 2025-02-10 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producer', '0002_postwastedetails_delete_producerinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='postwastedetails',
            name='category',
            field=models.CharField(default='Uncategorized', max_length=50),
        ),
        migrations.AddField(
            model_name='postwastedetails',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
