# Generated by Django 5.1.6 on 2025-02-10 04:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DisposalMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_name', models.CharField(max_length=50, unique=True)),
                ('is_custom', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FrequencyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('is_custom', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='WasteDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types_of_waste', models.CharField(choices=[('construction_and_demolition', 'Construction and Demolition'), ('organic', 'Organic'), ('plastic', 'Plastic'), ('paper_and_cardboard', 'Paper and Cardboard'), ('metal', 'Metal'), ('glass', 'Glass'), ('textile_and_fabric', 'Textile and Fabric'), ('electronic', 'Electronic'), ('medical', 'Medical'), ('chemical', 'Chemical'), ('automotive', 'Automotive'), ('mixed', 'Mixed'), ('agricultural', 'Agricultural'), ('biomedical', 'Biomedical')], max_length=100)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('disposal_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waste_details.disposalmethod')),
                ('frequency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waste_details.frequencytype')),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Waste Detail',
                'verbose_name_plural': 'Waste Details',
            },
        ),
    ]
