# Generated by Django 5.1.6 on 2025-02-10 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste_details', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wastedetails',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
