# Generated by Django 5.1.6 on 2025-02-10 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userprofile_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='media/logo/'),
        ),
    ]
